services:
  openclaw-gateway:
    volumes:
      - openclaw_home:/home/node
      - /Users/hungnguyen/.openclaw_z:/home/node/.openclaw
      - /Users/hungnguyen/.openclaw_z/workspace:/home/node/.openclaw/workspace
  openclaw-cli:
    volumes:
      - openclaw_home:/home/node
      - /Users/hungnguyen/.openclaw_z:/home/node/.openclaw
      - /Users/hungnguyen/.openclaw_z/workspace:/home/node/.openclaw/workspace
volumes:
  openclaw_home:
