services:
  openclaw-gateway:
    volumes:
      - openclaw_home:/home/node
      - C:\Users\hungg\.openclaw_z:/home/node/.openclaw
      - C:\Users\hungg\.openclaw_z\workspace:/home/node/.openclaw/workspace
  openclaw-cli:
    volumes:
      - openclaw_home:/home/node
      - C:\Users\hungg\.openclaw_z:/home/node/.openclaw
      - C:\Users\hungg\.openclaw_z\workspace:/home/node/.openclaw/workspace
volumes:
  openclaw_home:
